package com.codespace.ide.terminal

import android.content.Context
import java.io.File

class TerminalEnhancementManager(private val context: Context) {
    private val prefs = context.getSharedPreferences("terminal_enhancements", Context.MODE_PRIVATE)

    fun profileScriptPath(): File = File(context.filesDir, "terminal_profile.sh")

    fun ensureProfile(): String {
        val file = profileScriptPath()
        file.writeText(buildProfileScript())
        return file.absolutePath
    }

    fun backupProfile(): String? {
        val file = profileScriptPath()
        if (!file.exists()) ensureProfile()
        val backup = File(context.filesDir, "terminal_profile_backup.sh")
        backup.writeText(file.readText())
        return backup.absolutePath
    }

    fun restoreProfile(): String? {
        val backup = File(context.filesDir, "terminal_profile_backup.sh")
        if (!backup.exists()) return null
        val file = profileScriptPath()
        file.writeText(backup.readText())
        return file.absolutePath
    }

    fun setTheme(theme: String) {
        prefs.edit().putString("terminal_theme", theme).apply()
    }

    fun currentTheme(): String = prefs.getString("terminal_theme", "Dark") ?: "Dark"

    private fun buildProfileScript(): String = buildString {
        appendLine("# Auto-generated by VN Code terminal enhancements")
        appendLine("export VN_CODE_TERMINAL=1")
        appendLine("export VN_CODE_TERMINAL_THEME=${currentTheme()}")
        appendLine("export HISTSIZE=20000")
        appendLine("export HISTFILESIZE=20000")
        appendLine("export HISTCONTROL=ignoredups:erasedups")
        appendLine("alias ll='ls -la'")
        appendLine("alias la='ls -A'")
        appendLine("alias gs='git status'")
        appendLine("alias ga='git add'")
        appendLine("alias gc='git commit'")
        appendLine("alias gp='git push'")
        appendLine("alias ..='cd ..'")
        appendLine("alias ...='cd ../..'")
        appendLine("alias c='clear'")
        appendLine("alias py='python'")
        appendLine("if [ -f ~/.zshrc ]; then")
        appendLine("  echo '[terminal] shell profile ready' >/dev/null 2>&1")
        appendLine("fi")
    }
}
